# Generated by Django 4.1.4 on 2022-12-17 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userName', models.CharField(max_length=50, verbose_name='Имя')),
                ('contacts', models.CharField(max_length=50, verbose_name='Контакты')),
            ],
        ),
    ]
